#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kfcnew_development
  username: karemu200018
  password: mydb

test:
  <<: *default
  database: kfcnew_test
  username: karemu200018
  password: mydb

production:
  <<: *default
  database: kfcnew_production
  username: karemu200018
  password: mydb